services:
  fin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3344:8000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - ALPHAVANTAGE_API_KEY=
      - COIN_MARKETCAP_API_KEY=
      - FINNHUB_API_KEY=